### Theme: Dracula Dark (Tím than, hồng neon)

set $bg0         #282a36
set $bg1         #343746
set $bg2         #44475a
set $bg3         #6272a4
set $bg4         #798cb8
set $fg          #f8f8f2
set $gray        #6272a4
set $red         #ff5555
set $green       #50fa7b
set $yellow      #f1fa8c
set $blue        #8be9fd
set $purple      #bd93f9
set $aqua        #8be9fd
set $orange      #ffb86c
set $pink        #ff79c6

# target                 border    bg        text      indicator  child_border
client.focused           #ff79c6   #44475a   #f8f8f2   #bd93f9    #ff79c6
client.focused_inactive  #44475a   #282a36   #6272a4   #44475a    #44475a
client.unfocused         #343746   #282a36   #6272a4   #343746    #282a36
client.urgent            $red      $red      #f8f8f2   $red       $red
