### Theme: Graphite (Neutral Gray & Ivory)

set $bg0         #181818
set $bg1         #1c1c1c
set $bg2         #2d2d2d
set $bg3         #3a3a3a
set $bg4         #484848
set $fg          #dedcd1
set $gray        #9c9a92
set $red         #dd5353
set $green       #65bb30
set $yellow      #e5b567
set $blue        #dedcd1
set $purple      #9b87f5
set $aqua        #74abe2
set $orange      #c2c0b6

# target                 border    bg        text      indicator  child_border
client.focused           $bg2      $bg2      $fg       $orange    $blue
client.focused_inactive  $bg1      $bg1      $gray     $orange    $bg2
client.unfocused         $bg0      $bg0      $gray     $bg0       $bg0
client.urgent            $red      $red      $bg0      $orange    $red
