### Theme: Gruvbox Dark

set $bg0         #282828
set $bg1         #3c3836
set $bg2         #504945
set $bg3         #665c54
set $bg4         #7c6f64
set $fg          #ebdbb2
set $gray        #928374
set $red         #fb4934
set $green       #b8bb26
set $yellow      #fabd2f
set $blue        #83a598
set $purple      #d3869b
set $aqua        #8ec07c
set $orange      #fe8019

# target                 border    bg        text      indicator  child_border
client.focused           $bg2      $bg2      $blue     $orange    $blue
client.focused_inactive  $bg1      $bg1      $gray     $orange    $bg1
client.unfocused         $bg0      $bg0      $gray     $orange    $bg0
client.urgent            $red      $red      $bg0      $orange    $red
