### Theme: Monochrome (Nền đen chữ trắng)

set $bg0         #000000
set $bg1         #141414
set $bg2         #242424
set $bg3         #383838
set $bg4         #505050
set $fg          #ffffff
set $gray        #808080
set $red         #ff5555
set $green       #50fa7b
set $yellow      #f1fa8c
set $blue        #ffffff
set $purple      #bd93f9
set $aqua        #8be9fd
set $orange      #ffb86c

# target                 border    bg        text      indicator  child_border
client.focused           #ffffff   #141414   #ffffff   #ffffff    #ffffff
client.focused_inactive  #383838   #141414   #808080   #383838    #242424
client.unfocused         #242424   #000000   #808080   #242424    #141414
client.urgent            $red      $red      #000000   $red       $red
