### Theme: Sepia (Màu giấy cổ Sepia, chữ sẫm đen)

set $bg0         #f4ecd8
set $bg1         #e8dcbe
set $bg2         #dac9a3
set $bg3         #c4b087
set $bg4         #ad966d
set $fg          #2b2118
set $gray        #6b5643
set $red         #b83a28
set $green       #4f6d2b
set $yellow      #b07412
set $blue        #8f4e24
set $purple      #7d4366
set $aqua        #2b6f6f
set $orange      #b8521d

# target                 border    bg        text      indicator  child_border
client.focused           #8f4e24   #e8dcbe   #2b2118   #b8521d    #8f4e24
client.focused_inactive  #c4b087   #e8dcbe   #6b5643   #c4b087    #c4b087
client.unfocused         #dac9a3   #f4ecd8   #6b5643   #dac9a3    #dac9a3
client.urgent            #b83a28   #b83a28   #f4ecd8   #b83a28    #b83a28
client.placeholder       #e8dcbe   #e8dcbe   #6b5643   #e8dcbe    #e8dcbe
client.background        #f4ecd8
