### Theme: Tokyo Night (Dark - Night)

set $bg0         #1a1b26
set $bg1         #24283b
set $bg2         #2f3549
set $bg3         #414868
set $bg4         #565f89
set $fg          #c0caf5
set $gray        #565f89
set $red         #f7768e
set $green       #9ece6a
set $yellow      #e0af68
set $blue        #7aa2f7
set $purple      #bb9af7
set $aqua        #7dcfff
set $orange      #ff9e64

# target                 border    bg        text      indicator  child_border
client.focused           $bg2      $bg2      $blue     $orange    $blue
client.focused_inactive  $bg1      $bg1      $gray     $orange    $bg1
client.unfocused         $bg0      $bg0      $gray     $orange    $bg0
client.urgent            $red      $red      $bg0      $orange    $red
client.placeholder       $bg1      $bg1      $gray     $orange    $bg1
client.background        $bg0
