background_opacity 0.9
dim_opacity 0.7
# Colorscheme: Monochrome Black & White
background #000000
foreground #ffffff
selection_background #383838
selection_foreground #ffffff
cursor #ffffff
cursor_text_color #000000

# ANSI Colors
# Black
color0 #141414
color8 #666666
# Red
color1 #ff5555
color9 #ff6e6e
# Green
color2 #50fa7b
color10 #69ff94
# Yellow
color3 #f1fa8c
color11 #ffffa5
# Blue
color4 #ffffff
color12 #d8d8d8
# Magenta / Purple
color5 #bd93f9
color13 #d6acff
# Cyan
color6 #8be9fd
color14 #a4ffff
# White
color7 #e0e0e0
color15 #ffffff
