# Giao diện mặc định của phiên GNOME (Ubuntu): Yaru đỏ
org.gnome.desktop.interface gtk-theme 'Yaru-red-dark'
org.gnome.desktop.interface icon-theme 'Yaru-red-dark'
org.gnome.desktop.interface cursor-theme 'Yaru'
org.gnome.desktop.interface cursor-size 24
org.gnome.desktop.interface font-name 'Ubuntu Sans 11'
org.gnome.desktop.interface document-font-name 'Ubuntu Sans 11'
org.gnome.desktop.interface monospace-font-name 'Ubuntu Sans Mono 11'
org.gnome.desktop.interface color-scheme 'prefer-dark'
org.gnome.desktop.interface accent-color 'red'
org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'
