# Dracula
$theme_bg0 = rgb(282a36)
$theme_bg1 = rgb(343746)
$theme_bg2 = rgb(44475a)
$theme_fg = rgb(f8f8f2)
$theme_gray = rgb(6272a4)
$theme_red = rgb(ff5555)
$theme_green = rgb(50fa7b)
$theme_yellow = rgb(f1fa8c)
$theme_blue = rgb(8be9fd)
$theme_purple = rgb(bd93f9)
$theme_aqua = rgb(8be9fd)
$theme_orange = rgb(ffb86c)
$theme_active_border = rgb(ff79c6)
$theme_inactive_border = rgb(44475a)
$theme_panel = rgba(343746ee)
$theme_workspace_active = rgba(ff79c622)
$theme_workspace_inactive = rgba(282a3666)
