# Gruvbox Dark
$theme_bg0 = rgb(1d2021)
$theme_bg1 = rgb(282828)
$theme_bg2 = rgb(3c3836)
$theme_fg = rgb(ebdbb2)
$theme_gray = rgb(928374)
$theme_red = rgb(fb4934)
$theme_green = rgb(b8bb26)
$theme_yellow = rgb(fabd2f)
$theme_blue = rgb(83a598)
$theme_purple = rgb(d3869b)
$theme_aqua = rgb(8ec07c)
$theme_orange = rgb(fe8019)
$theme_active_border = rgb(83a598)
$theme_inactive_border = rgb(504945)
$theme_panel = rgba(282828ee)
$theme_workspace_active = rgba(83a59822)
$theme_workspace_inactive = rgba(1d202166)
