# Monochrome
$theme_bg0 = rgb(000000)
$theme_bg1 = rgb(141414)
$theme_bg2 = rgb(242424)
$theme_fg = rgb(ffffff)
$theme_gray = rgb(808080)
$theme_red = rgb(ff5555)
$theme_green = rgb(50fa7b)
$theme_yellow = rgb(f1fa8c)
$theme_blue = rgb(ffffff)
$theme_purple = rgb(bd93f9)
$theme_aqua = rgb(8be9fd)
$theme_orange = rgb(ffb86c)
$theme_active_border = rgb(ffffff)
$theme_inactive_border = rgb(383838)
$theme_panel = rgba(141414ee)
$theme_workspace_active = rgba(ffffff12)
$theme_workspace_inactive = rgba(00000066)
