# Tokyo Night
$theme_bg0 = rgb(1a1b26)
$theme_bg1 = rgb(24283b)
$theme_bg2 = rgb(2f3549)
$theme_fg = rgb(c0caf5)
$theme_gray = rgb(565f89)
$theme_red = rgb(f7768e)
$theme_green = rgb(9ece6a)
$theme_yellow = rgb(e0af68)
$theme_blue = rgb(7aa2f7)
$theme_purple = rgb(bb9af7)
$theme_aqua = rgb(7dcfff)
$theme_orange = rgb(ff9e64)
$theme_active_border = rgb(7aa2f7)
$theme_inactive_border = rgb(414868)
$theme_panel = rgba(24283bee)
$theme_workspace_active = rgba(7aa2f722)
$theme_workspace_inactive = rgba(1a1b2666)
