general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
}

label {
    monitor =
    text = $TIME
    font_size = 72
    font_family = JetBrainsMono Nerd Font
    color = rgb(ffffff)
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(ffffff)
    inner_color = rgb(141414)
    font_color = rgb(ffffff)
    check_color = rgb(50fa7b)
    fail_color = rgb(ff5555)
    fade_on_empty = false
    placeholder_text = Mật khẩu...
    position = 0, -60
    halign = center
    valign = center
}
