source = ~/.config/hypr/theme.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
}

label {
    monitor =
    text = $TIME
    font_size = 72
    font_family = JetBrainsMono Nerd Font
    color = $theme_fg
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = $theme_active_border
    inner_color = $theme_bg1
    font_color = $theme_fg
    check_color = $theme_green
    fail_color = $theme_red
    fade_on_empty = false
    placeholder_text = Mật khẩu...
    position = 0, -60
    halign = center
    valign = center
}
